#!/bin/bash

TMP=".tmp"


if [ "$USER" != "root" ]; then
	sudo $0
	exit
fi

function copy {
	mkdir -p $TMP/$2
	cp -r $1/* $TMP/$2 
}

rm -fR $TMP
mkdir $TMP

copy "palm/activities" "/etc/palm/activities/com.palm.service.whatsapp"
copy "palm/db" "/etc/palm/db/kinds"
copy "palm/tempdb" "/etc/palm/tempdb/kinds"
copy "palm/accounts" "/usr/palm/public/accounts/com.palm.whatsapp"
copy "palm/dbus" "/usr/share/dbus-1/system-services"
copy "palm/roles" "/usr/share/ls2/roles/prv"
copy "palm/roles" "/usr/share/ls2/roles/pub"
copy "service" "/usr/palm/services/com.palm.service.whatsapp"
copy "app" "/usr/palm/applications/com.palm.app.whatsapp.config"


cd $TMP

gnutar --exclude-vcs -zcf data.tar.gz ./etc ./usr

cat > control << EOF
Package: com.palm.whatsapp
Version: 1.0.0
Section: misc
Priority: optional
Architecture: all
Maintainer: Bruno Orcha <gimcoo@gmail.com>
Description: Whatsapp Synergy Service
EOF

gnutar -zcf control.tar.gz ./control

echo "2.0" > debian-binary

rm ../com.palm.whatsapp_1.0.0_all.ipk
ar -r ../com.palm.whatsapp_1.0.0_all.ipk ./debian-binary ./data.tar.gz ./control.tar.gz
cd ..

novacom -d tcp put file:///tmp/com.palm.whatsapp_1.0.0_all.ipk < com.palm.whatsapp_1.0.0_all.ipk
novacom -d tcp run "file:///usr/bin/ipkg install /tmp/com.palm.whatsapp_1.0.0_all.ipk"
novacom -d tcp run "file:///usr/bin/killall LunaSysMgr"

